
export const CREATE_ORDER_REQUEST="CREATE_ORDER_REQUEST";
export const CREATE_ORDER="CREATE_ORDER";
export const CREATE_ORDER_FAIL="CREATE_ORDER_FAIL";
export const CREATE_ORDER_RESET="CREATE_ORDER_RESET";

export const ORDER_DETAIL_REQUEST ="ORDER_DETAIL_REQUEST";
export const ORDER_DETAIL ="ORDER_DETAIL";
export const ORDER_DETAIL_FAIL="ORDER_DETAIL_FAIL";

export const MY_LIST_ORDER_REQUEST="MY_LIST_ORDER_REQUEST";
export const MY_LIST_ORDER="MY_LIST_ORDER";
export const MY_LIST_ORDER_FAIL="MY_LIST_ORDER_FAIL";

export const LIST_ORDER="LIST_ORDER";
export const LIST_ORDER_FAIL="LIST_ORDER_FAIL";


