export const PRODUCT_LIST ='PRODUCT_LIST';
export const PRODUCT_FAILURE ="PRODUCT_FAILURE";

export const PRODUCT_DETAILS ='PRODUCT_DETAILS';
export const PRODUCT_DETAILS_FAILURE ="PRODUCT_DDETAILS_FAILURE";

export  const PRODUCT_DELETE ="PRODUCT_DELETE";
export const PRODUCT_DELETE_FAIL="PRODUCT_DELETE_FAIL";

 export const PRODUCT_CREATE="PRODUCT_CREATE";
 export const PRODUCT_CREATE_FAIL="PRODUCT_CREATE_FAIL";
 export const PRODUCT_CREATE_RESET="PRODUCT_CREATE_RESET";


export const PRODUCT_UPDATE="PRODUCT_UPDATE";
export const PRODUCT_UPDATE_FAIL="PRODUCT_UPDATE_FAIL";
export const PRODUCT_UPDATE_RESET="PRODUCT_UPDATE_RESET";





