export const USER_LOGIN='USER_LOGIN';
export const USER_SIGNOUT='USER_SIGNOUT';
export const USER_REGISTER='USER_REGISTER';

export const USER_INFO_REQUEST="USER_INFO_REQUEST";
export const USER_INFO='USER_INFO';
export const USER_INFO_FAIL='USER_INFO_FAIL';

export const UPDATE_PROFILE_REQUEST="UPDATE_PROFILE_REQUEST";
export const UPDATE_PROFILE="UPDATE_PROFILE";
export const UPDATE_PROFILE_FAIL="UPDATE_PROFILE_FAIL";
export const PROFILE_RESET="PROFILE_RESET";


export const USER_LIST_REQUEST ="USER_LIST_REQUEST";
export const USER_LIST="USER_LIST";
export const USER_LIST_FAIL = "USER_LIST_FAIL";
export const USER_LIST_RESET = "USER_LIST_RESET";

export const USER_DELETE="USER_DELETE";
export const USER_DELETE_FAIL="USER_DELETE_FAIL"

